/// Generated by AssetsRefGenerator on 2021/09/18
class Res {
  static const String google = "images/google.png";
  static const String load = "images/load.gif";
  static const String splash = "images/splash.json";
  static const String voice_bar = "images/voice_bar.json";
  static const String voice_splash = "images/voice_splash.json";
}
